### ISSUE TITLE
[Not issue] Introduction YouTube video

### ISSUE THREAD

**Issue by emisjerry** [devbean/obsidian-wordpress#11]
Hi, 我錄製了YouTube影片介紹這個外掛，希望有更多的Blogger使用： 

https://youtu.be/7YECfr_W1WM

**Comment by devbean** [comment]
多谢！我想可以把影片放在 README 里面，不知是否同意？

**Comment by emisjerry** [comment]
當然！感謝你的貢獻。

**Comment by emisjerry** [comment]
B站剛剛upload了，網址: https://www.bilibili.com/video/BV1FT411A77m/?vd_source=8d3e1ef8cd3aab146af84cfad2f5076f

**Comment by devbean** [comment]
已经合并到 README，感谢！
