### ISSUE TITLE
remember password

### ISSUE THREAD

**Issue by Yuelioi** [devbean/obsidian-wordpress#12]
This plugin is amazing, I really like this kind of workflow.

but if I can remember the username and password, load categories page directly, That will be cool.

And I use REST mode, It can only show 10 categories, I dont know why. in this video , It show more categories (https://youtu.be/7YECfr_W1WM)

Maybe we can add username and password in plugin settings?

Other suggestions:

-tags
-custom url link?

**Comment by Yuelioi** [comment]
草 翻了下评论发现是国人

哥,咱能跳过那个登录界面么,每次都要输下密码好累啊

**Comment by devbean** [comment]
我也想记住密码来着，但密码只能明文保存，如果启用某些同步插件的话，有些是能同步插件数据的，这个密码就可能泄露到网上…不过加一个选项自担风险好像也是可以的吧

**Comment by Yuelioi** [comment]
> 我也想记住密码来着，但密码只能明文保存，如果启用某些同步插件的话，有些是能同步插件数据的，这个密码就可能泄露到网上…不过加一个选项自担风险好像也是可以的吧

是的 这点风险和方便比起来，不值一提😉

**Comment by devbean** [comment]
新发布的 0.5.0 版本添加了记住密码的选项，帮忙测试一下，感谢！

**Comment by Yuelioi** [comment]
> 新发布的 0.5.0 版本添加了记住密码的选项，帮忙测试一下，感谢！

已测试,完美运行.非常感谢!
