### ISSUE TITLE
404 on miniorange Rest API

### ISSUE THREAD

**Issue by pyjoku** [devbean/obsidian-wordpress#13]
I had tested the miniorange REST API concept before. 
but it stopped working. the xmlrpc is functional
I use version 2.4.0 on miniorange and 0.5.0 on Wordpress publish.

It did work before. So i am not sure what happened.

app.js:1 Uncaught (in promise) Error: Request failed, status 404
    at new t (app.js:1:1454507)
    at VN (app.js:1:1454662)
    at app.js:1:1455339
    at app.js:1:235078
    at Object.next (app.js:1:235183)
    at s (app.js:1:233922)
t @ app.js:1
VN @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
step @ plugin:obsidian-wordpress:65
fulfilled @ plugin:obsidian-wordpress:53
Promise.then (async)
step @ plugin:obsidian-wordpress:65
eval @ plugin:obsidian-wordpress:66
__async @ plugin:obsidian-wordpress:50
eval @ plugin:obsidian-wordpress:23994
eval @ plugin:obsidian-wordpress:21949
(anonymous) @ app.js:1

the link the in console looks like the URL ist both API endpoint put together
like 
wp-jason/wp/v2/postswp-jason/wp/v2/categories

hope this helps in understanding the probem

**Comment by devbean** [comment]
404 means the URL not found.

It seems you set wrong WordPress URL in settings dialog. The URL should be something like "https://blog.example.com/" but yours seems to be "https://blog.example.com/wp-json/wp/v2/posts" thus "wp-json/wp/v2/categories" append to the incorrect URL result as "wp-json/wp/v2/postswp-json/wp/v2/categories".
