### ISSUE TITLE
"\\" in LaTex is not recongnized when publish to wordpress 

### ISSUE THREAD

**Issue by DEAN-Cherry** [devbean/obsidian-wordpress#14]
I have some `LaTex` like this
$$
\begin{aligned}
6
& = 1 + 2 + 3 
\\
& = 2 + 4
\\
& = 3 + 3
\end{aligned}
$$
where I used `\\`  to linefeed. It will be converted to `\` when publise to WordPress, and this is annoying.

-------------------------------------------------------==--------------------------------------------------

在 `LaTex` 中使用 `\\` 作为换行符时，发布至 WordPress 会被解析为 `\`, 公式失效

**Comment by devbean** [comment]
可以提供一个有公式失效的完整 markdown 文档吗？可以直接发邮箱 devbean@outlook.com

**Comment by DEAN-Cherry** [comment]
> 

已发送
[test.md](https://github.com/devbean/obsidian-wordpress/files/9504210/test.md)

**Comment by devbean** [comment]
0.11.0 增加了 MathJax 的支持，请测试一下。

PS: 参数里面有关于 MathJax 输出格式的相关设置，如果 WordPress 没有安装 MathJax 的插件，可以选择直接输出 SVG 格式。
