### ISSUE TITLE
[Feature Request] 支持文章的更新

### ISSUE THREAD

**Issue by happyeddie** [devbean/obsidian-wordpress#15]
非常棒的插件，好像也是目前唯一可用的 wp 插件 ！！！

不知道是我使用方式的不对，还是没有这个功能，针对同一个文档，多次点击 wp icon，会发布多次
当然我的期望是如果针对同一篇文章的多次 publish，期望是更新，而不是新建一篇

**Comment by devbean** [comment]
目前是没有修改的功能，每次都是新增。如果做更新的话，需要把 wp 返回的 id 记录下来，并与 ob 的文档关联，这部分需要额外的设计才可以的了

**Comment by musicleaf** [comment]
期待这个功能，每次修改发布后都是新ID，的确有点冗余，求支持更新

**Comment by gslnzfq** [comment]
是否可以在文档的front-matter种写入发布的网址和文章的id呢？

**Comment by gslnzfq** [comment]
已经实现，由开发者合并后可用 #24

**Comment by devbean** [comment]
@gslnzfq 之前的 pull request 没有合并，因为有一些小问题，主要是 REST API 和 XML-RPC 的返回值不同，您的 pull reuqest 没有处理。我根据您的修改重新提交了代码，现在已经发布了版本。请测试一下。非常感谢！

**Comment by gslnzfq** [comment]
> @gslnzfq 之前的 pull request 没有合并，因为有一些小问题，主要是 REST API 和 XML-RPC 的返回值不同，您的 pull reuqest 没有处理。我根据您的修改重新提交了代码，现在已经发布了版本。请测试一下。非常感谢！

测试了下没有问题了，👍
