### ISSUE TITLE
无法使用插件

### ISSUE THREAD

**Issue by Jeffreyone** [devbean/obsidian-wordpress#17]
登录账号密码时毫无反馈

**Comment by devbean** [comment]
增加了密码错误的提示，请更新测试

**Comment by emisjerry** [comment]
我剛剛的狀況一樣無法登入，確認帳密是正確的，以前都能正常使用：

![image](https://user-images.githubusercontent.com/131511/207496586-185c0393-fd7b-48f4-9829-a19e0a93e81d.png)

**Comment by devbean** [comment]
> 我剛剛的狀況一樣無法登入，確認帳密是正確的，以前都能正常使用：
> 
> ![image](https://user-images.githubusercontent.com/131511/207496586-185c0393-fd7b-48f4-9829-a19e0a93e81d.png)

可以提供一下详细信息吗？403 的话一般就是用户名或密码错误。
