### ISSUE TITLE
401 error with REST API - Invalid username or password

### ISSUE THREAD

**Issue by SuperBoss9** [devbean/obsidian-wordpress#20]
Hi!

Trying to get this plugin working.
WP 6.1.1

Trying to post a note via REST API and receive the following error: "Invalid username or password".

At the server logs I see the following:
[05/Jan/2023:17:11:39 +0300] "GET /wp-json/wp/v2/users?search=username HTTP/1.1" 401 208 "-" "obsidian.md" "blog.kvv213.com"

In the developing console the following:

![image](https://user-images.githubusercontent.com/53711021/210801835-17c87cad-d9c7-4a5f-a342-fbac739484d0.png)

What shall I do in order to make it work? Already tried to re do the application password.

PS. XMLRPC works

**Comment by devbean** [comment]
Response code 401 usually means incorrect username or password. Please check it again.

PS: I have tested application password for my testing WP and it seems OK.

**Comment by SuperBoss9** [comment]
Checked it twice on one server and also on its test copy twice :) The same error.
Different names, different password applications (with and without spaces).

**Comment by devbean** [comment]
I'm not sure why. Is it possible you create a temp user and send me the username and password by email to devbean@outlook.com?

**Comment by devbean** [comment]
Thank you! I have figered out this problem. When you use application passwords, the username should be your WP username, not the application password name. So you need to input your WP username which passwords belongs to and the application password generated. Please check it again.

**Comment by SuperBoss9** [comment]
Yes, I have to confirm that I was too silly in reading of the documents :) Thank you.

**Comment by le0hard** [comment]
I had a problem with a 401 error because I first put ‘http’ in the address instead of ‘https’. 
I was careless. 
Maybe this will be useful to someone :-)
