### ISSUE TITLE
FEATURE REQUEST: Ability to select different sites

### ISSUE THREAD

**Issue by ricraftis** [devbean/obsidian-wordpress#21]
Would it be possible to include a number of sites in the plugin. I have several, but can only publish to one at present?

Many thanks for considering.

**Comment by devbean** [comment]
Yes, profile is in the feature list.

**Comment by ricraftis** [comment]
Many thanks

**Comment by devbean** [comment]
Please check latset version 0.12.0.

**Comment by ricraftis** [comment]
Many thanks. There were a few interested on Mastadon PKM. I will do a post and hopefully a video soon.
