### ISSUE TITLE
Feature Request: support for tags

### ISSUE THREAD

**Issue by kdmurray** [devbean/obsidian-wordpress#22]
Would it be possible for the plugin to read metadata like front-matter from an Obsidian MD file and include that as post metadata for things like tags when the note is published?

**Comment by devbean** [comment]
The latest version supports tags. Please test for it. Thank you!

**Comment by kdmurray** [comment]
Tags worked great. Would it be possible to add support for title: as well so I can override the note title?

Use case - my Obsidian note titles have things like dates in them that I don't want in the published article.

**Comment by devbean** [comment]
I have supported `title` field in front matter in 0.10.0, please check it out.

**Comment by kdmurray** [comment]
Works perfectly. Thank you @devbean!
