### ISSUE TITLE
Feature Request: Link to WordPress article on confirmation

### ISSUE THREAD

**Issue by kdmurray** [devbean/obsidian-wordpress#23]
I would like to be able to have a link from Obsidian that I can click that takes me to the WordPress admin panel and opens up the post in edit mode:

/wp-admin/post.php?post={{post-id}}&action=edit

This will make doing final edits from the WP editor and setting any other metadata quicker and easier.

**Comment by devbean** [comment]
I have added this feature in 0.10.0, please check it out.

**Comment by kdmurray** [comment]
Works as designed. Thanks!
