### ISSUE TITLE
发布的时候，可以读取yaml区域的tags,增加文章的标签么

### ISSUE THREAD

**Issue by musicleaf** [devbean/obsidian-wordpress#25]
目前使用的mwb进行wordpress发布，他支持将yaml区域的标签发布到wordpss的标签中，功能很帅，求支持。

<img width="427" alt="image" src="https://user-images.githubusercontent.com/35360006/213493024-b648b44c-c8cf-4804-a6d3-fbbe0f34ef29.png">

**Comment by devbean** [comment]
#22

**Comment by devbean** [comment]
新版本已经发布了，请测试一下

**Comment by musicleaf** [comment]
测试没有问题。 已经可以读取yaml区域的tags
