### ISSUE TITLE
[Bug?] 筆記內容有百分號時無法publish

### ISSUE THREAD

**Issue by emisjerry** [devbean/obsidian-wordpress#26]
Hi,

筆記內容有百分號(%)時會無法公佈，將之改成全形百分號就能正常公佈。
請確認此狀況。

Thanks.

**Comment by devbean** [comment]
可以详细描述下是怎样的内容吗？或者将出错的笔记部分内容贴出来。我测试使用 % 没有异常。

**Comment by emisjerry** [comment]
我下次再遇到此狀況時再回報吧。Thanks.

**Comment by emisjerry** [comment]
剛好遇到百分號的問題了。

- log檔是DevTools的內容，把%DATE% %TIME% 的百分號刪掉就能正常publish
[obsidian-console.log](https://github.com/devbean/obsidian-wordpress/files/10703469/obsidian-console.log)

- md檔
[Windows  copy newer.md](https://github.com/devbean/obsidian-wordpress/files/10703474/Windows.copy.newer.md)
