### ISSUE TITLE
[Issue] 筆記內容有百分號時publish 400 Bad request問題

### ISSUE THREAD

**Issue by emisjerry** [devbean/obsidian-wordpress#27]
剛好遇到百分號的問題了。

- log檔是DevTools的內容，把%DATE% %TIME% 的百分號刪掉就能正常publish
[obsidian-console.log](https://github.com/devbean/obsidian-wordpress/files/10703469/obsidian-console.log)

- md檔
[Windows  copy newer.md](https://github.com/devbean/obsidian-wordpress/files/10703474/Windows.copy.newer.md)

_Originally posted by @emisjerry in https://github.com/devbean/obsidian-wordpress/issues/26#issuecomment-1425132456_

**Comment by emisjerry** [comment]
如下內容就會接到400的錯誤:

```
# test2
test

%DATE%
```

**Comment by devbean** [comment]
我这边测试没有问题，可以正常发布。您的插件版本是不是最新的？是不是使用默认选项发布的？看您提供的日志，category 的 ID 是 22，请确认这个 ID 是否正确。按照 WordPress XML-RPC 协议的文档，返回 400 可能是因为 category ID 找不到。
