### ISSUE TITLE
数学公式中的&发布后会被加上转义符、双反斜杠\\会变成单反斜杠\

### ISSUE THREAD

**Issue by fantab01** [devbean/obsidian-wordpress#29]
第一个问题，比如输入`$$\begin{bmatrix}a&d\b&d\end{bmatrix}$$`
到wordpress上会变成`$$\begin{bmatrix}a&amp;d\b&amp;d\end{bmatrix}$$`

第二个问题，比如输入`$$\begin{cases}\vec{v}\\\vec{v_1}\end{cases}$$`会变成`$$\begin{cases}\vec{v}\\vec{v_1}\end{cases}$$`
输入`$$\begin{cases}\vec{v}\\vec{v_1}\end{cases}$$`会变成`$$\begin{cases}\vec{v}\vec{v_1}\end{cases}$$`

然后这个公式就会渲染失败，还得手动删掉`amp;`和加上一个`\`，不知作者有没有办法解决这两个小问题，提前感谢~

**Comment by fantab01** [comment]
第二个问题的两个事例又少显示少了一个反斜杠......我修改一下
输入$$\begin{cases}\vec{v}\.\.\vec{v_1}\end{cases}$$会变成$$\begin{cases}\vec{v}\.\vec{v_1}\end{cases}$$
输入$$\begin{cases}\vec{v}\.\vec{v_1}\end{cases}$$会变成$$\begin{cases}\vec{v}\vec{v_1}\end{cases}$$

**Comment by devbean** [comment]
0.11.0 增加了 MathJax 的支持，请测试一下。

PS: 参数里面有关于 MathJax 输出格式的相关设置，如果 WordPress 没有安装 MathJax 的插件，可以选择直接输出 SVG 格式。

**Comment by devbean** [comment]
#14

**Comment by fantab01** [comment]
我这里测试没问题了，谢谢作者更新~
