### ISSUE TITLE
[Feature Request] Remove YAML area

### ISSUE THREAD

**Issue by emisjerry** [devbean/obsidian-wordpress#3]
Please remove the entire YAML section before sending.

**Comment by devbean** [comment]
Could you please make it clear? I'm not sure about YAML section.

**Comment by emisjerry** [comment]
For example, my file's content:

```
---
aliases:
tags: [ obsidian, noteTaking ]
wordpress-category: obsidian
wordpress-mode: publish
---
# My Title

my content
```

After press Publish button, the plugin send out the file content without the YAML section (starts and ends with `---`).
And maybe you can read wordpress-category as the category in published article, and change the mode to publish rather than draft by wordpress-mode.

Sorry for my poor English. Could i use Chinese next time?

**Comment by devbean** [comment]
感谢澄清！

我一直不知道 wordpress 还可以在文章中通过 YAML 的方式指定分类这种。当时在做插件的时候，使用一个右侧的面板，就是为了在以后的版本支持界面中选择分类和发布这种选项。如果能够在文章中设置也不错的。现在是用 marked 将 markdown 转换成 HTML 来做发布的，应该是 marked 把 YAML 移除了。

您可以方便提供一下有关在 wordpress 中通过 YAML 设置的相关文档的页面吗？

**Comment by emisjerry** [comment]
抱歉，描述得不夠清楚。

YAML區這些是在Obsidian筆記裡寫的，我建議你的plugin可以讀YAML裡的特定欄位(如wordpress-mode)來變更新增WordPress文章時的固定設定(目前是草稿)。

傳出時YAML內容若不事先刪除，WordPress文章就會含有這些內容，而WordPress是不認識YAML的，這樣每次都必須手動再去刪除。

**Comment by devbean** [comment]
原来是这样。

按照我的理解，您是建议在 obsidian 的笔记里面添加 YAML，用于配置 wordpress 栏目、发布模式等信息。

原本我的计划是会在插件的面板中，使用 GUI 读取 wordpress 的栏目等以便用户设置。比起 YAML，这样可能会更方便一些。

**Comment by emisjerry** [comment]
有這個plugin options當然很棒。

但不同的筆記可能需要不同的分類(如生活分類，職場分類等)，如此選項就很難處理了。

如果做在YAML區就可以跟模板整合，透過模板建立筆記時可選擇要publish到那個分類，這樣就更方便了。

**Comment by devbean** [comment]
我的意思是在右侧有一个面板，现在 plugin option 里面是有 Show icon in sidebar 的选项，开启之后，左侧会出现 wordpress 的 logo 按钮，点击 wordpress logo 按钮之后，右侧会出现一个发布的面板（现在只有一个 Publish 按钮）。我的计划是在这个面板中添加分类等信息，每次发布时可以由此设置。

**Comment by devbean** [comment]
请升级到 0.4.0 版本，现在可以选择一个 category 和 status。
