### ISSUE TITLE
MathJax 输出格式问题

### ISSUE THREAD

**Issue by fe1w0** [devbean/obsidian-wordpress#31]
# 设置
开启 SVG模式
<img width="667" alt="image" src="https://user-images.githubusercontent.com/50180586/220827235-b2c7b9d0-a55c-40c0-9cb9-d02e3270ca6f.png">

公式SVG生成成功，但原文换行没了。

Obsidian 原文：
<img width="596" alt="image" src="https://user-images.githubusercontent.com/50180586/220827358-ca6925bd-a9a3-4672-951b-eb5ab0de6bb9.png">

Wordpress 中直接预览文章：
<img width="821" alt="image" src="https://user-images.githubusercontent.com/50180586/220827567-e7c05244-d7eb-40cb-be60-d45a80375352.png">

编辑状态下 SVG不显示，再次保持会导致公式SVG丢失。
<img width="942" alt="image" src="https://user-images.githubusercontent.com/50180586/220827733-e20779d7-d2d6-42a5-b957-a85493edb111.png">

**Comment by devbean** [comment]
可以发一些公式以及上下文部分，看看 obsidian 的 markdown 是怎么写的。然后，“编辑状态下 SVG不显示” 是指的 WordPress 编辑器的编辑状态吗？

**Comment by fe1w0** [comment]
是的。好的，作者大大。

> 可以发一些公式以及上下文部分，看看 obsidian 的 markdown 是怎么写的。然后，“编辑状态下 SVG不显示” 是指的 WordPress 编辑器的编辑状态吗？

[test.md](https://github.com/devbean/obsidian-wordpress/files/10810563/test.md)

**Comment by devbean** [comment]
我这边测试的 SVG 是有换行的。不知道你的 WordPress 页面有没有发布出来？可以看看你那边的页面代码，是不是生成的有问题？

第二个问题，WordPress 的编辑器就是不支持 SVG 的，所以切换到编辑状态不能显示。可能需要安装某些插件才能支持吧

**Comment by fe1w0** [comment]
好的，谢谢，作者

Cheng Liang ***@***.***> 于2023年2月23日周四 14:32写道：
