### ISSUE TITLE
No publish button?

### ISSUE THREAD

**Issue by kdmurray** [devbean/obsidian-wordpress#37]
After pushing the sidebar button to begin the publishing process there doesn't seem to be a way to actually confirm the publish from the dialog that's presented. Screenshot attached.

Hitting the 'x' to close the dialog dismisses it as expected. No post appears on Wordpress, no confirmation and no error message.

![image](https://user-images.githubusercontent.com/247251/231021352-004f7efe-cc5b-4fe3-a548-7abb9d846a1a.png)

**Comment by devbean** [comment]
This is a bug if newly install this plugin. I have released a new version to fix this bug. Please upgrade your plugin to check out if it is fixed. Sorry again.

**Comment by kdmurray** [comment]
Fantastic. Thanks again for your fast response! 
Love your work! :)
