### ISSUE TITLE
conversion issue for image tag

### ISSUE THREAD

**Issue by SEG91** [devbean/obsidian-wordpress#38]
on version 13 got an issue on img tag
&lt;img style='float:left; height: 24px; width: 24px; margin-right: 4px;' src='https://cepheus-jdr.fr/icon/svg/medal-skull.svg'/&gt; 
instead of <img style='float:left; height: 24px; width: 24px; margin-right: 4px;' src='https://cepheus-jdr.fr/icon/svg/medal-skull.svg'/>

i experience this issue since few days

**Comment by devbean** [comment]
Did you mean embeded HTML code was escaped when posted to WordPress?

**Comment by SEG91** [comment]
Hello

Yes the symbole < & > of the image tag are transform to &lt &gt
Only in windows
It works fine on mac

Le sam. 15 avr. 2023 à 15:22, Cheng Liang ***@***.***> a
écrit :

**Comment by devbean** [comment]
I have add a new setting option named enable HTML, enable this will send HTML tags directly to WordPress. Please update the plugin to see if it works well.

**Comment by SEG91** [comment]
Good
Will be testing today
Will keep you posted
Thanks

Le lun. 17 avr. 2023 à 04:43, Cheng Liang ***@***.***> a
écrit :
