### ISSUE TITLE
可以把发布wordpress的文章状态为已发布吗？现在是草稿状态

### ISSUE THREAD

**Issue by wonfull** [devbean/obsidian-wordpress#4]
我试着发布了两篇文章，发现同步到wordpress的文章状态是草稿的状态，如果想要公开文章，还要再次打开wordpress，将文章发布出去，如果我没有记错，无论是哪种发布方式，都可以把文章设置为『已发布』的。

**Comment by devbean** [comment]
是可以的，主要是怕万一格式有问题，直接按照 publish 类型发布的话可能会不好，所以暂时全部按照 draft 发送的。马上会添加一个参数选择是否按照 publish 类型发送。

**Comment by wonfull** [comment]
好的，多谢
