### ISSUE TITLE
使用rest api报用户名/密码错误

### ISSUE THREAD

**Issue by KLFTESPACE** [devbean/obsidian-wordpress#46]
![微信截图_20230702194852](https://github.com/devbean/obsidian-wordpress/assets/39041589/2adfe3e5-db88-4112-93aa-2f550e4a7a11)
![微信截图_20230702194910](https://github.com/devbean/obsidian-wordpress/assets/39041589/43f05325-9ab2-431c-a8aa-d8e67f2ab512)
你好，我使用xml-rpc可以成功，但是使用REST API Authentication by miniOrange会报用户名/密码错误。不知道这个是什么原因。

**Comment by KLFTESPACE** [comment]
在设置miniorange时网址测试是可以的，用的是http://43.143.149.34/index.php/wp-json/wp/v2/posts/1

**Comment by devbean** [comment]
用户名密码错误，控制台有报错吗？或者试试直接用 Application Passwords？这样就不需要安装插件了

**Comment by KLFTESPACE** [comment]
> 用户名密码错误，控制台有报错吗？或者试试直接用 Application Passwords？这样就不需要安装插件了

已解决，是因为插件那会我忘记finish了，一直在测试界面那里。。。
application passwords那里需要https这种，我暂时还没有备案

**Comment by devbean** [comment]
但是 HTTPS 的证书申请并不需要备案的，没有备案应该也是可以开通 HTTPS 的吧，不过需要用 Let's Encrypt 这样的国外服务，不能用国内的证书服务

**Comment by KLFTESPACE** [comment]
> 

第一次用，不是很熟悉。可以查一查。
我还有另一个问题，就是阅读源码后发现插件是根据用户名和密码直接生成token来进行验证的，如果自己搭了一个平台（采用的是JWT生成验证码），想要把文档上传到该平台上该怎么做？理论上不应该是这边输入账号密码后返回相应的token吗？还是也和这个一样自行生成token？

**Comment by devbean** [comment]
这个插件因为是只针对 WordPress，所以按照 WordPress 的要求生成，WordPress 要求的生成算法就是插件中写的。对于自己的平台，就要按照平台要求的 token 生成算法去生成对应的 token

**Comment by myzhongguo** [comment]
我的一直报404无论是xmlrpc还是应用程序密码，应用程序密码postman测试接口没问题，应该是插件把auth base方式的账号和密码转义request参数有问题
