### ISSUE TITLE
WP plugin giving error "Incorrect User/PW" when trying to Publish

### ISSUE THREAD

**Issue by Callileah** [devbean/obsidian-wordpress#5]
I recently installed the plugin.   When testing the Publish function to my WP site, which is hosted on wordpress.com i.e. https://(me).wordpress.com, it gives error msg "Post Publish Failed. 403 : Username or Password incorrect".
I've checked, they are in fact correct.
So I'm wondering if the real issue is how my WP site is hosted....  It's a a sub-domain on wordpress.com.  Could this be the problem?

Thanks in advance for help with this.

**Comment by devbean** [comment]
Hi,
I have tested the plugin with wordpress.com and find it works with wordpress.com using XML-RPC.
You could open obsidian console by pressing CTRL+SHIFT+I (Windows), open console tab to find out if there is anything wrong. The endpoint should be https://(me).wordpress.com/xmlrpc.php . The following XML code should contain your user name and password as following,
```
<?xml version="1.0"?>
<methodCall>
  <methodName>wp.newPost</methodName>
  <params>
    <param>
      <value>
        <array>
          <data>
            <value>
              <i4>0</i4>
            </value>
            <value>
              <string>***YOUR WP USER NAME***</string>
            </value>
            <value>
              <string>***YOUR XML-ENCODED WP PW***</string>
            </value>
            <value>
              <struct>
                <member>
                  <name>post_type</name>
                  <value>
                    <string>post</string>
                  </value>
                </member>
...
```
Is there anything incorrect? Is there any special characters in your password?

**Comment by Callileah** [comment]
Ok...just trying your instructions now.  been working on other stuff for last few days.  Sorry for not getting back to you sooner.
Just checked everything you suggested and it looks correct. There's no special chars in my PW.
This is what gets generated:
**_DevTools failed to load source map: Could not parse content for app://obsidian.md/obsidian.css.map: Unexpected end of JSON input_**
VM149:21301 Endpoint: https://callileah.wordpress.com/xmlrpc.php
VM149:21303 <?xml version="1.0"?>
<methodCall>
  <methodName>wp.newPost</methodName>
  <params>
    <param>
      <value>
        <array>
          <data>
            <value>
              <i4>0</i4>
            </value>
            <value>
              <string>callileah</string>
            </value>
            <value>
              <string>(my PW)</string>
            </value>
            <value>
              <struct>
                <member>
                  <name>post_type</name>
                  <value>
                    <string>post</string>
                  </value>
                </member>
                <member>
                  <name>post_status</name>
                  <value>
                    <string>draft</string>
                  </value>
                </member>
                <member>
                  <name>post_title</name>
                  <value>
                    <string>Untitled</string>
                  </value>
                </member>
                <member>
                  <name>post_content</name>
                  <value>
                    <string>&lt;p&gt;Test Post to Wordpress Site....&lt;/p&gt;
</string>
                  </value>
                </member>
              </struct>
            </value>
          </data>
        </array>
      </value>
    </param>
  </params>
</methodCall>



Error MSG:

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <fault>
    <value>
      <struct>
        <member>
          <name>faultCode</name>
          <value><int>403</int></value>
        </member>
        <member>
          <name>faultString</name>
          <value><string>Incorrect username or password.</string></value>
        </member>
      </struct>
    </value>
  </fault>
</methodResponse>

**Comment by Callileah** [comment]
Also, this appears before the section you reference:

VM149:21298 Object
DevTools failed to load source map: Could not parse content for app://obsidian.md/obsidian.css.map: Unexpected end of JSON input
VM149:21301 Endpoint: https://callileah.wordpress.com/xmlrpc.php
VM149:21303 <?xml version="1.0"?>
<methodCall>
  <methodName>wp.newPost</methodName>
-----
Could this be the problem??

**Comment by Callileah** [comment]
Hi..  I have contacted WP and they have checked that XML-RPC is ON and seems to be working.  So, I'm flummoxed.
Any suggestions?

**Comment by devbean** [comment]
XML-RPC should wok with all themes so that's not the problem. `DevTools failed to load source map` is OK for `.map` files are used  for debugging. Endpoint seems OK, too. I'm not sure what problem is. I released a new version of the plugin adding more console logs so could you please update the plugin to see if there is any useful logs at this version?

**Comment by Eviepayne** [comment]
I seem to also have this issue.
I don't see any issues.
Checking console, /var/log, wordpress plugin logs, etc.
it looks like it's just not working.

**Comment by devbean** [comment]
So is this solved?
