### ISSUE TITLE
[Feature Request] Custom XMLRPC name

### ISSUE THREAD

**Issue by Eviepayne** [devbean/obsidian-wordpress#9]
For security reasons I change my XMLRPC from the normal xmlrpc.php and change it to something obfuscated and hard to guess.

I would like to have the ability to change that without editing the code manually.
I tried adding the code necessary but it seems like there's something I'm missing, since I keep getting an error "Invalid '!' in opening tag"
Not sure why the API is returning the main html page.
From my logs the customxml string is properly returned in the endpoint.

Figure you have better familiarity and would know exactly what I'm missing.

**Comment by devbean** [comment]
I have added a setting value named XML-RPC path. Please check it to see if it works.
